name: Update NFT Leaderboard Data (Infura)

# This 'on' block is the key part.
# It enables the workflow to run on a schedule AND be run manually.
on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch: # THIS LINE ENABLES THE MANUAL "Run workflow" BUTTON

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script to update leaderboard
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          INFURA_PROJECT_SECRET: ${{ secrets.INFURA_PROJECT_SECRET }}
        run: python update_script.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git add leaderboard.json
          if ! git diff --staged --quiet; then
            git commit -m "Update leaderboard data"
            git push
          else
            echo "No changes to commit."
          fi
